admin_pages/urls.py
from django.urls import path

from admin_pages import views

urlpatterns = [
    path("", views.AdminView.as_view(), name="index"),
    path("export/activities/", views.ExportActivities.as_view(), name="activities.csv"),
    path("export/slots/", views.ExportSlots.as_view(), name="slots.csv"),
    path("email/", views.NewEmail.as_view(), name="email_new"),
    path("info", views.SiteInfo.as_view(), name="info"),
]

home/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views.generic import RedirectView, TemplateView

from home import views

sitemaps = {"static_pages": views.StaticViewSitemap}

urlpatterns = [
    path(
        "activites/nouvelle/",
        views.ActivitySubmissionView.as_view(),
        name="activity_submission",
    ),
    path("favicon.ico", RedirectView.as_view(url="/static/imgs/favicon.ico")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path(
        "admin_pages/",
        include(("admin_pages.urls", "admin_pages"), namespace="admin_pages"),
    ),
    path("authens/logout", views.LogoutView.as_view(), name="logout"),
    path("authens/", include("authens.urls")),
    path("", include(("pages.urls", "pages"), namespace="pages")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from .views import HTMLPageView

urlpatterns = [
    path("", HTMLPageView.as_view(), {"slug": ""}, name="home"),
    path("<slug:slug>/", HTMLPageView.as_view(), name="html_page"),
]

site48h/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
]

home/forms.py
from django import forms

from home import models
from shared.forms import FormRenderMixin


class ActivitySubmissionForm(FormRenderMixin, forms.ModelForm):
    class Meta:
        model = models.ActivityModel
        fields = (
            "title",
            "act_type",
            "game_type",
            "description",
            "host_name",
            "host_email",
            "host_info",
            "must_subscribe",
            "max_participants",
            "min_participants",
            "duration",
            "desired_slot_nb",
            "available_friday_evening",
            "available_friday_night",
            "available_saturday_morning",
            "available_saturday_afternoon",
            "available_saturday_evening",
            "available_saturday_night",
            "available_sunday_morning",
            "available_sunday_afternoon",
            "constraints",
            "needs",
            "comments",
        )

    def clean(self):
        cleaned_data = super().clean()
        maxi = None
        mini = None
        if cleaned_data is not None:
            maxi = cleaned_data.get("max_participants")
            mini = cleaned_data.get("min_participants")
        if maxi is not None and mini is not None and maxi != 0 and mini > maxi:
            raise forms.ValidationError(
                "Le nombre minimal de participants est supérieur au nombre maximal",
                code="invalid_order",
            )
        return cleaned_data

    def save(self, *args, commit=True, **kwargs):
        """Enregistre l'activité dans la base de données"""
        activity = models.ActivityModel(
            **self.cleaned_data,
        )
        if commit:
            activity.save()
        return activity

home/views.py
from datetime import timedelta
from typing import Any, Dict

from authens.views import LogoutView as AuthensLogoutView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sitemaps import Sitemap
from django.core.mail import send_mail
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.views.generic import FormView

from pages.models import HTMLPageModel
from site48h import settings as site_settings
from site_settings.models import SiteSettings

from .forms import ActivitySubmissionForm
from .models import SlotModel


def get_planning_context() -> Dict[str, Any]:
    """Returns the context dict needed to display the planning"""
    settings = SiteSettings.load()
    context = dict()
    context["planning"] = SlotModel.objects.filter(on_planning=True).order_by("title")
    if settings.date_start is not None:
        context["friday"] = settings.date_start.day
        context["saturday"] = (settings.date_start + timedelta(days=1)).day
        context["sunday"] = (settings.date_start + timedelta(days=2)).day
    else:
        context["friday"] = 1
        context["saturday"] = 2
        context["sunday"] = 3
    return context


# ==============================
# Activity Submission Form
# ==============================


class ActivitySubmissionView(LoginRequiredMixin, FormView):
    """Vue pour proposer une activité"""

    template_name = "activity_submission.html"
    form_class = ActivitySubmissionForm
    success_url = reverse_lazy("pages:html_page", kwargs={"slug": "activites"})

    @staticmethod
    def submission_check() -> bool:
        """Vérifie si le formulaire est ouvert ou non"""
        settings = SiteSettings.load()
        return settings.activity_submission_open

    def not_open(self, request: HttpRequest) -> HttpResponse:
        """Appelé quand le formulaire est désactivé"""
        messages.error(request, "La soumission d'activité est désactivée")
        return redirect(self.success_url, permanent=False)

    def get_initial(self) -> Dict[str, str]:
        init = super().get_initial()
        user = self.request.user
        init.update({"host_name": user.username, "host_email": user.email})
        return init

    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        if not self.submission_check():
            return self.not_open(request)
        return super().get(self, request, *args, **kwargs)

    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        if not self.submission_check():
            return self.not_open(request)
        form = self.form_class(request.POST)
        if not form.is_valid():
            context = self.get_context_data()
            context["form"] = form
            return render(request, self.template_name, context)

        activity = form.save()
        activity.host = request.user
        activity.save()

        messages.success(
            request,
            "Votre activité a bien été enregistrée. Elle sera affichée sur le site après relecture par les admins.",
        )
        settings = SiteSettings.load()
        if settings.notify_on_activity_submission and settings.contact_email:
            message = render_to_string(
                "new_activity_email.txt",
                {
                    "user": request.user,
                    "activity": activity,
                    "signature": site_settings.EMAIL_SIGNATURE,
                },
            )
            send_mail(
                site_settings.USER_EMAIL_SUBJECT_PREFIX + "Nouvelle activité proposée",
                message,
                from_email=None,
                recipient_list=[settings.contact_email],
            )

        return redirect(self.success_url, permanent=False)


# ==============================
# Sitemap
# ==============================


class StaticViewSitemap(Sitemap):
    """Vue générant la sitemap.xml du site"""

    changefreq = "monthly"

    def items(self):
        """list of pages to appear in sitemap"""
        return [
            ("pages:home", {}),
        ] + [("pages:html_page", {"slug": obj.slug}) for obj in HTMLPageModel.objects.all() if obj.slug]

    def location(self, item):
        """real url of an item"""
        name, kwargs = item
        return reverse(name, kwargs=kwargs)

    def priority(self, obj):
        """priority to appear in sitemap"""
        # Priorize home page over the rest in search results
        if obj == "home" or obj == "":
            return 0.8
        else:
            return None  # defaults to 0.5 when unset


class LogoutView(AuthensLogoutView):
    next_page = reverse_lazy("pages:home")

home/templates/_planning.html
<div id="planning" style="margin-left: calc(-49vw + 50%); width: 97vw; background-color: white; padding: 10px;"></div>
<!--
In order to limit the planning's width, we cheat using the timeline's groups
I.E we set all dates to the first day (Friday) and set groups allowing vertical display:
-->
<script type="text/javascript">
	// https://visjs.org/
	// DOM element where the Timeline will be attached
	const container = document.getElementById('planning');

	const groups = new vis.DataSet([
		{id: 0, content: "Ven.", order: 0},
		{id: 1, content: "Sam.", order: 1},
		{id: 2, content: "Dim.", order: 2},
	]);

	// Items in the timeline
	const items = new vis.DataSet([
	{% for slot in planning %}
		{% if slot.start_day == slot.end_day %}
			{
				content: '<div style="background-color: yellow;"><a class="hidden" href="#{{ slot.activity.slug }}"><div><strong>{{ slot }}</strong><br>{{ slot.room|default:"" }}</div></a></div>',
				title: '<strong>{{ slot }}</strong><br>{{ slot.room|default:"" }}',
				start: '{{ slot.planning_start|date:"Y-m-d H:i:s"}}',
				align: 'left',
				group: {{ slot.start_day }},
				end:'{{ slot.planning_end|date:"Y-m-d H:i:s"}}',
				className: "color-{{ slot.color }}",
			},
		{% else %} // activity spans multiple days
			{
				content: '<a class="hidden" href="#{{ slot.activity.slug }}"><div><strong>{{ slot }}</strong><br>{{ slot.room|default:"" }}</div></a>',
				title: '<strong>{{ slot }}</strong><br>{{ slot.room|default:"" }}',
				start: '{{ slot.planning_start|date:"Y-m-d H:i:s"}}',
				align: 'left',
				group: {{ slot.start_day }},
				end:'{{ settings.date_2|date:"Y-m-d"}} 04:00:00',
				className: "color-{{ slot.color }}",
			},
			{
				content: '<a class="hidden" href="#{{ slot.activity.slug }}"><div><strong>{{ slot }}</strong><br>{{ slot.room|default:"" }}</div></a>',
				title: '<strong>{{ slot }}</strong><br>{{ slot.room|default:"" }}',
				start: '{{ settings.date_start|date:"Y-m-d"}} 04:00:00',
				align: 'left',
				group: {{ slot.end_day }},
				end:'{{ slot.planning_end|date:"Y-m-d H:i:s"}}',
				className: "color-{{ slot.color }}",
			},
		{% endif %}
	{% endfor %}
	]);

	// Configuration for the Timeline
	const start = '{{ settings.date_start|date:"Y-m-d"}} 08:00:00';
	const end = '{{ settings.date_start|date:"Y-m"}}-{{ saturday }} 04:00:00';
	const options = {
		showMajorLabels: false,
		showCurrentTime: false,
		locale: "fr",
		groupOrder: "order",
		start: start,
		min: start,
		end: end,
		max: end,
		selectable: false,
		zoomable: false,
	};

	// Create a Timeline
	const timeline = new vis.Timeline(container, items, options);
	timeline.setGroups(groups);
	// timeline.on('select', function (properties) {
	// 	alert('selected items: ' + properties.items);
	// });
</script>

<style>
	.vis-item {
		background-color: var(--color_bg_1);
		color: white;
	}
	.vis-item-content {
		width: 100%;
	}
	.vis-item a, .vis-item a:link, .vis-item a:visited {
		text-decoration: none;
		color: white;
		width: 100%;
	}
	.vis-item a div {
		width: 100%;
	}
	.vis-item:hover {
		background-color: var(--color_bg_2);
	}
	.vis-time-axis .grid.vis-odd {
		background: #444;
	}

	/* Color specific things */
	:root {
		/* red */
		--color_1: #e84855;
		--color_1_hover: #da1b2b;
		--color_1_fg: white;

		/* orange */
		--color_2: #dd7230;
		--color_2_hover: #c15d1f;
		--color_2_fg: white;

		/* yellow */
		--color_3: #f9dc5c;
		--color_3_hover: #f7d126;
		--color_3_fg: black;

		/* green */
		--color_4: #7cae7a;
		--color_4_hover: #5f8b55;
		--color_4_fg: white;

		/* blue */
		--color_5: #3185fc;
		--color_5_hover: #0467f1;
		--color_5_fg: white;

		/* dark blue */
		--color_6: #4c4c7c;
		--color_6_hover: #26263c;
		--color_6_fg: white;

		/* black */
		--color_7: #483D3F;
		--color_7_hover: #2c2627;
		--color_7_fg: white;

	}
	.vis-item.color-a {
		background-color: var(--color_1);
	}
	.vis-item.color-a a, .vis-item.color-a a:link, .vis-item.color-a a:visited {
		color: var(--color_1_fg);
	}
	.vis-item.color-a:hover {
		background-color: var(--color_1_hover)
	}
	.vis-item.color-b {
		background-color: var(--color_2);
	}
	.vis-item.color-b a, .vis-item.color-b a:link, .vis-item.color-b a:visited {
		color: var(--color_2_fg);
	}
	.vis-item.color-b:hover {
		background-color: var(--color_2_hover)
	}
	.vis-item.color-c {
		background-color: var(--color_2);
	}
	.vis-item.color-c a, .vis-item.color-c a:link, .vis-item.color-c a:visited {
		color: var(--color_2_fg);
	}
	.vis-item.color-c:hover {
		background-color: var(--color_2_hover)
	}
	.vis-item.color-c {
		background-color: var(--color_3);
	}
	.vis-item.color-c a, .vis-item.color-c a:link, .vis-item.color-c a:visited {
		color: var(--color_3_fg);
	}
	.vis-item.color-c:hover {
		background-color: var(--color_3_hover)
	}
	.vis-item.color-d {
		background-color: var(--color_4);
	}
	.vis-item.color-d a, .vis-item.color-d a:link, .vis-item.color-d a:visited {
		color: var(--color_4_fg);
	}
	.vis-item.color-d:hover {
		background-color: var(--color_4_hover)
	}
	.vis-item.color-e {
		background-color: var(--color_5);
	}
	.vis-item.color-e a, .vis-item.color-e a:link, .vis-item.color-e a:visited {
		color: var(--color_5_fg);
	}
	.vis-item.color-e:hover {
		background-color: var(--color_5_hover)
	}
	.vis-item.color-f {
		background-color: var(--color_6);
	}
	.vis-item.color-f a, .vis-item.color-f a:link, .vis-item.color-f a:visited {
		color: var(--color_6_fg);
	}
	.vis-item.color-f:hover {
		background-color: var(--color_6_hover)
	}
	.vis-item.color-g {
		background-color: var(--color_7);
	}
	.vis-item.color-g a, .vis-item.color-g a:link, .vis-item.color-g a:visited {
		color: var(--color_7_fg);
	}
	.vis-item.color-g:hover {
		background-color: var(--color_7_hover)
	}

</style>
{% if settings.has_caption %}
<div class="caption">
	<p><strong>Légende :</strong></p>
	<ul style="list-style-type: none; margin-left:-20px">
		{% if settings.caption_red %}<li><span style="background-color: var(--color_1);">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> {{ settings.caption_red }}</li>{% endif %}
		{% if settings.caption_orange %}<li><span style="background-color: var(--color_2);">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> {{ settings.caption_orange }}</li>{% endif %}
		{% if settings.caption_yellow %}<li><span style="background-color: var(--color_3);">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> {{ settings.caption_yellow }}</li>{% endif %}
		{% if settings.caption_green %}<li><span style="background-color: var(--color_4);">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> {{ settings.caption_green }}</li>{% endif %}
		{% if settings.caption_blue %}<li><span style="background-color: var(--color_5);">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> {{ settings.caption_blue }}</li>{% endif %}
		{% if settings.caption_dark_blue %}<li><span style="background-color: var(--color_6);">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> {{ settings.caption_dark_blue }}</li>{% endif %}
		{% if settings.caption_black %}<li><span style="background-color: var(--color_7);">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> {{ settings.caption_black }}</li>{% endif %}
	</ul>
</div>
{% endif %}
{% if settings.planning_file %}
	<div><p><a class="button" href="{{ settings.planning_file.url }}"><i class="fa fa-download"></i> Télécharger le planning</a></p></div>
{% endif %}

home/templates/activity_submission.html
{% extends "base.html" %}
{% load static %}

{% block nav_activite %}current{% endblock %}

{% block "content" %}
{% if form.errors or form.non_field_errors %}
<ul class="messagelist">
	<li class="error">Ce formulaire contient des erreurs.</li>
</ul>
{% endif %}

<h2>Proposer une activité</h2>

{{ form.non_field_errors }}

<form method="post" action="{% url 'activity_submission' %}">
	{% csrf_token %}

	<ul class="messagelist">
		<li class="info">
			Les informations publiques (qui apparaîtrons sur la page
			<a href="{% url 'pages:html_page' slug='activites' %}">activités</a>) sont
			celles <span class="underline">soulignées</span>.<br>
			Les autres ne serons vues que par les orgas.
		</li>
	</ul>

	<table>
		<tr>
			<td><strong class="underline">Titre&nbsp;:</strong></td>
			<td> {{ form.title }}</td>
		</tr>
		<tr>
			<td><strong class="underline">Type d'activité&nbsp;:</strong></td>
			<td> {{ form.act_type }}</td>
		</tr>
		<tr>
			<td><strong class="underline">Type de jeu&nbsp;:</strong></td>
			<td> {{ form.game_type }}</td>
		</tr>
	</table>

	<p><strong class="underline">Description&nbsp;:</strong> ce texte sera affiché sur la page
		<a href="{% url 'pages:html_page' slug='activites' %}">activités</a> pour présenter votre activité.
	</p>
	{{ form.description }}

	<h3>Organisateurs</h3>

	<table>
		<tr>
			<td><strong class="underline">Nom&nbsp;:</strong></td>
			<td> {{ form.host_name }}</td>
		</tr>
		<tr>
			<td><strong class="underline">Email&nbsp;:</strong></td>
			<td> {{ form.host_email }}</td>
		</tr>
		<tr>
			<td><strong>Compte associé&nbsp;:&nbsp;</strong></td>
			<td> {{ request.user.username }}</td>
		</tr>
	</table>

	<p>
		L'email de votre compte sera le principal moyen de contact.
		Si vous ne souhaitez pas qu'il soit affiché, précisez le ci-dessous.
		Vous pouvez également spécifier d'autres moyens de contact, ainsi que d'autres
		organisateurs si vous êtes plusieurs.
	</p>

	{{ form.host_info }}

	<h3>Participants et inscription</h3>

	<table>
		<tr>
			<td><strong class="underline">Nécessite une inscription&nbsp;:</strong></td>
			<td> {{ form.must_subscribe }}
				(si vrai, votre email sera affiché pour que les intéressés vous contacte)
			</td>
		</tr>
		<tr>
			<td><strong class="underline">Nombre max de participants&nbsp;:</strong></td>
			<td> {{ form.max_participants }} (mettez 0 pour illimité)</td>
		</tr>
		{% if form.max_participants.errors %}<tr>
			<td></td>
			<td>{{ form.max_participants.errors }}</td>
		</tr>{% endif %}
		<tr>
			<td><strong class="underline">Nombre min de participants&nbsp;:</strong></td>
			<td> {{ form.min_participants }}</td>
		</tr>
		{% if form.min_participants.errors %}<tr>
			<td></td>
			<td>{{ form.min_participants.errors }}</td>
		</tr>{% endif %}
	</table>

	<h3>Durée et créneaux</h3>

	<table>
		<tr>
			<td><strong class="underline">Durée approximative&nbsp;:</strong></td>
			<td> {{ form.duration }} (format hh:mm:ss)</td>
		</tr>
		{% if form.duration.errors %}<tr>
			<td></td>
			<td>{{ form.duration.errors }}</td>
		</tr>{% endif %}
		<tr>
			<td><strong>Nombre de crénaux souhaités&nbsp;:</strong></td>
			<td> {{ form.desired_slot_nb }}</td>
		</tr>
		{% if form.desired_slot_nb.errors %}<tr>
			<td></td>
			<td>{{ form.desired_slot_nb.errors }}</td>
		</tr>{% endif %}
		<tr>
			<td><strong>Disponibilités&nbsp;:</strong></td>
		</tr>
		<tr>
			<td>&nbsp;-&nbsp;Vendredi soir&nbsp;:</td>
			<td>{{ form.available_friday_evening }}</td>
		</tr>
		<tr>
			<td>&nbsp;-&nbsp;Vendredi nuit&nbsp;:</td>
			<td>{{ form.available_friday_night }}</td>
		</tr>
		<tr>
			<td>&nbsp;-&nbsp;Samedi matin&nbsp;:</td>
			<td>{{ form.available_saturday_morning }}</td>
		</tr>
		<tr>
			<td>&nbsp;-&nbsp;Samedi après-midi&nbsp;:</td>
			<td>{{ form.available_saturday_afternoon }}</td>
		</tr>
		<tr>
			<td>&nbsp;-&nbsp;Samedi soir&nbsp;:</td>
			<td>{{ form.available_saturday_evening }}</td>
		</tr>
		<tr>
			<td>&nbsp;-&nbsp;Samedi nuit&nbsp;:</td>
			<td>{{ form.available_saturday_night }}</td>
		</tr>
		<tr>
			<td>&nbsp;-&nbsp;Dimanche matin &nbsp;:</td>
			<td>{{ form.available_sunday_morning }}</td>
		</tr>
		<tr>
			<td>&nbsp;-&nbsp;Dimanche après-midi&nbsp;:</td>
			<td>{{ form.available_sunday_afternoon }}</td>
		</tr>
	</table>

	<p>Si vous avez des contraintes particulières, vous pouvez les préciser ici&nbsp;:</p>

	{{ form.constraints }}

	<h3>Modalités pratiques</h3>

	<ul>
		<li>Vous faut-il une ou plusieurs salles&nbsp;?</li>
		<li>Vous faut-il du matériel spécial&nbsp;?</li>
		<li>Quels outils faut-il pour participer&nbsp;?</li>
		<li>Et tout autre besoin de ce type...</li>
	</ul>

	{{ form.needs }}

	<h3>Commentaires</h3>

	<p>D'autres choses à nous communiquer qui ne rentre pas dans les champs précédents&nbsp;?</p>

	{{ form.comments }}

	<h3>Soumettre</h3>

	<p>L'activité n'est plus modifiable une fois soumise. Les administrateurs la reliront avant de l'afficher sur le site.
	</p>

	<div class="flex">
		<input type="submit" value="Soumettre mon activité">
		<a class="button" href="{% url 'pages:home' %}">Annuler</a>
	</div>

</form>
{% endblock %}

home/templates/base.html
{% spaceless %}
{% load static %}
<!doctype html>
<html lang="fr">
	<head>
		<!-- WEBSITE VERSION {{ constants.WEBSITE_FULL_VERSION }} -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<title>{% block title %}48h des Jeux{% endblock %}</title>
		<meta name="description" content="Informations sur les 48h des jeux{% if settings.date_start %}, édition {{ settings.date_start.year }}{% endif %}">
		<meta name="keywords" content="ENS Ulm Jeux événement COF {% if settings.date_start %}{{ settings.date_start.year }} {% endif %}">
		<link rel="icon" type="image/png" href="{% static 'imgs/favicon.ico' %}">

		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}?v={{ constants.CSS_VERSION }}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome-all.min.css' %}">
		{% block head %}{% endblock %}
	</head>
	<body>
		<header>
			<div class="logo">
				<h1><a href="{% url 'pages:home' %}"><img src="{% static 'imgs/logo.svg' %}" alt="logo">&nbsp;48h des jeux&nbsp;</a></h1>
			</div>
			<div id="head_main_infos">
				<div id="location">ENS Ulm</div>
				<div id="date">{% if settings.date_start %}
				{% if settings.date_end %}
				{% if settings.date_end.month != settings.date_start.month %}
				{{ settings.date_start|date:"j N" }}-{{ settings.date_end|date:"j N Y" }}
				{% else %}
				{{ settings.date_start.day }}-{{ settings.date_end }}
				{% endif %}
				{% else %}
				{{ settings.date_start }}
				{% endif %}
				{% else %}
				Date non-fixée
				{% endif %}</div>
			</div>
		</header>

		<script type="text/javascript">
			function toggle_menu() {
				var nav = document.getElementById("nav");
				if (nav.className === "") {
					nav.className += "responsive";
				} else {
					nav.className = "";
				}
			}
		</script>

		<nav id="nav">
			<a href="{% url 'pages:home' %}" rel="text/html"
				class="{% block nav_home %}{% endblock %}">
				Accueil
			</a>
			<a href="{% url 'pages:html_page' slug='activites' %}" rel="text/html"
				class="{% block nav_activite %}{% endblock %}">
				Activités
			</a>
			<a href="{% url 'pages:html_page' slug='faq' %}" rel="text/html"
				class="{% block nav_faq %}{% endblock %}">
				FAQ
			</a>
			{% if request.user.is_authenticated %}
				<a href="{% url 'authens:logout' %}"
					class="{% block nav_profile %}{% endblock %}">
					Déconnexion
				</a>
			{% else %}
				<a href="{% url 'authens:login' %}"
					class="{% block nav_login %}{% endblock %}">
					Connexion
				</a>
			{% endif %}
			{% if user.is_superuser %}
			<a href="{% url 'admin_pages:index' %}"
				class="{% block nav_admin %}{% endblock %}">
				Administration
			</a>
			{% endif %}
			<a href="javascript:void(0);" class="icon" onclick="toggle_menu()">
				<i class="fa fa-bars"></i>
			</a>
		</nav>

		<main>
			{% if messages %}
			<ul class="messagelist">
				{% for message in messages %}
					<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
				{% endfor %}
			</ul>
			{% endif %}
			{% if settings.global_message %}
				{% if settings.global_message_as_html %}
					{{ settings.global_message|safe }}
				{% else %}
					<ul class="messagelist"><li class="info">{{ settings.global_message }}</li></ul>
				{% endif %}
			{% endif %}

			{% block "content" %}
			{% endblock %}
		</main>

		<footer>
			<div id="sponsors">
				<a class="external" href="https://www.ens.psl.eu/">
					<img src="{% static 'imgs/ens_psl.png' %}"
						alt="École Normale Supérieure de Paris | Université Paris Sciences et Lettres"
						title="École Normale Supérieure de Paris | Université Paris Sciences et Lettres"
					/>
				</a>
				<a class="external" href="https://cof.ens.fr/">
					<img src="{% static 'imgs/cof.svg' %}"
						alt="COF de l'ENS"
						title="COF de l'ENS"
					/>
				</a>
			</div>

			<p>
				{% if settings.contact_email %}
				Pour tout problème, contacter&nbsp;:<br><span class="antispam">{{ settings.contact_email_reversed }}</span>
				<br>
				{% endif %}
				<a href="{% url 'pages:html_page' slug='legal' %}">Mentions légales</a>
			</p>
		</footer>

	</body>
</html>
{% endspaceless %}