admin_pages/urls.py
from django.urls import path

from admin_pages import views

urlpatterns = [
    path("", views.AdminView.as_view(), name="index"),
    path("export/activities/", views.ExportActivities.as_view(), name="activities.csv"),
    path("export/slots/", views.ExportSlots.as_view(), name="slots.csv"),
    path("email/", views.NewEmail.as_view(), name="email_new"),
    path("info", views.SiteInfo.as_view(), name="info"),
]

home/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views.generic import RedirectView, TemplateView

from home import views

sitemaps = {"static_pages": views.StaticViewSitemap}

urlpatterns = [
    path(
        "activites/nouvelle/",
        views.ActivitySubmissionView.as_view(),
        name="activity_submission",
    ),
    path("favicon.ico", RedirectView.as_view(url="/static/imgs/favicon.ico")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path(
        "admin_pages/",
        include(("admin_pages.urls", "admin_pages"), namespace="admin_pages"),
    ),
    path("authens/logout", views.LogoutView.as_view(), name="logout"),
    path("authens/", include("authens.urls")),
    path("", include(("pages.urls", "pages"), namespace="pages")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from .views import HTMLPageView

urlpatterns = [
    path("", HTMLPageView.as_view(), {"slug": ""}, name="home"),
    path("<slug:slug>/", HTMLPageView.as_view(), name="html_page"),
]

site48h/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
]

admin_pages/models.py
# from django.db import models

# Create your models here.

admin_pages/forms.py
from django import forms
from django.conf import settings


class SendEmailForm(forms.Form):
    """Formulaire pour un envoie d'email
    à tous les utilisateurs"""

    subject = forms.CharField(
        max_length=100,
        required=True,
        label="Sujet",
        initial=settings.USER_EMAIL_SUBJECT_PREFIX,
        strip=True,
    )
    text = forms.CharField(label="Contenu", strip=True, widget=forms.Textarea)

admin_pages/views.py
from typing import Any, Dict, List, Optional, Tuple

from authens.models import User
from django import VERSION
from django.conf import settings
from django.contrib import messages
from django.core.mail import mail_admins, send_mass_mail
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.template.defaultfilters import date as django_date
from django.urls import reverse_lazy
from django.views.generic import FormView, TemplateView

from admin_pages.forms import SendEmailForm
from home import models
from home.views import get_planning_context
from shared.views import CSVWriteView, SuperuserRequiredMixin
from site_settings.models import Colors, SiteSettings

# ==============================
# Main Admin views
# ==============================


class AdminView(SuperuserRequiredMixin, TemplateView):
    template_name = "admin.html"

    def get_metrics(self):
        year = models.get_year()
        acts = models.ActivityModel.objects.filter(year=year)
        slots_in = models.SlotModel.objects.filter(activity__year=year)

        class metrics:
            users = User.objects.filter(is_active=True).count()

            activites = acts.count()
            displayed = acts.filter(display=True).count()
            act_ins = acts.filter(display=True, must_subscribe=True).count()

            slots = slots_in.count()

        return metrics

    def format_ok(self, message: str) -> str:
        """Mise en forme d'un check passé avec succès"""
        return '<li class="success">' + message + "</li>"

    def format_error(self, message: str, errors: Optional[List[str]] = None) -> str:
        """Mise en forme d'un check qui échoue"""
        if errors is not None:
            for err in errors:
                message += "<br> &bullet;&ensp; " + err
        return '<li class="error">' + message + "</li>"

    Conflicts = List[Tuple[models.SlotModel, models.SlotModel]]

    def get_conflicts(self) -> Conflicts:
        """Returns a list of overlapping slot pairs"""
        year = models.get_year()
        slots = models.SlotModel.objects.filter(activity__year=year)
        conflicts = []
        for i, slot_1 in enumerate(slots):
            for slot_2 in slots[i + 1 :]:
                if slot_1.conflicts(slot_2):
                    conflicts.append((slot_1, slot_2))
        return conflicts

    def check_hidden_activities(self) -> str:
        """Vérification du planning et de la répartition des activités:
        Vérifie que des activités ne soient pas masquées"""
        year = models.get_year()
        hidden_activites = models.ActivityModel.objects.filter(display=False, year=year)
        errors = []
        for act in hidden_activites:
            errors.append("{}".format(act))
        if errors:
            return self.format_error("Certaines activités ne sont pas affichées&nbsp;:", errors)
        return self.format_ok("Toutes les activités sont affichées")

    def check_planning_slots_nb(self) -> str:
        """Vérification du planning:
        Vérifie que toutes les activités ont le bon nombre de créneaux
        dans le planning"""
        errors = []
        year = models.get_year()
        activities = models.ActivityModel.objects.filter(year=year)
        for activity in activities:
            nb_wanted = activity.desired_slot_nb
            nb_got = activity.slots.count()
            if nb_wanted != nb_got:
                errors.append('"{}" souhaite {} crénaux mais en a {}.'.format(activity.title, nb_wanted, nb_got))
        if errors:
            return self.format_error("Certaines activités ont trop/pas assez de crénaux&nbsp;:", errors)
        return self.format_ok("Toutes les activités ont le bon nombre de crénaux")

    def check_planning_slot_conflicts(self, conflicts: Conflicts) -> str:
        """Vérification du planning:
        Vérifie qu'il n'y a pas d'orga gérant plusieurs activités simultanément"""
        errors = []
        for slot1, slot2 in conflicts:
            conflict_text = "'{}' (le {} UTC) et '{}' (le {} UTC)".format(
                slot1, django_date(slot1.start, "l à H:i"), slot2, django_date(slot2.start, "l à H:i")
            )
            if slot1.activity.host is not None and slot1.activity.host == slot2.activity.host:
                errors.append("L'utilisateur '{}' organise {}".format(slot1.activity.host, conflict_text))
            elif slot1.activity.host_name is not None and slot1.activity.host_name == slot2.activity.host_name:
                errors.append("'{}' organise {}".format(slot1.activity.host_name, conflict_text))
            elif slot1.activity.host_email == slot2.activity.host_email:
                errors.append("'{}' organise {}".format(slot1.activity.host_email, conflict_text))
        if errors:
            return self.format_error("Certains organisteurs gèrent plusieurs créneaux simultanément&nbsp;:", errors)
        return self.format_ok(
            "Aucun organisateur ne gèrent de créneaux simultanés.<br>(Ne compare que les orgas principaux, pas les éventuels additionels)"
        )

    def get_context_data(self, *args, **kwargs) -> Dict[str, Any]:
        conflicts = self.get_conflicts()
        settings = SiteSettings.load()
        planning_validations = ""
        if settings.display_planning:
            planning_validations += self.format_ok("Le planning est affiché")
        else:
            planning_validations += self.format_error("Le planning n'est pas affiché")
        planning_validations += self.check_hidden_activities()
        planning_validations += self.check_planning_slots_nb()
        planning_validations += self.check_planning_slot_conflicts(conflicts)

        context = super().get_context_data(*args, **kwargs)
        context["django_version"] = VERSION
        context["metrics"] = self.get_metrics()
        context["planning_validation"] = planning_validations
        context["planning_validation_errors"] = '<li class="error">' in planning_validations
        context.update(get_planning_context())
        return context


# ==============================
# DB Export Views
# ==============================


class ExportActivities(SuperuserRequiredMixin, CSVWriteView):
    filename = "activites_48h"
    model = models.ActivityModel
    fields = [
        # The key is "host_id" but listed as "host" in auto-found field names
        # which leads to an error...
        "id",
        "display",
        "title",
        "act_type",
        "game_type",
        "description",
        "desc_as_html",
        "host_id",
        "host_name",
        "host_email",
        "host_info",
        "show_email",
        "must_subscribe",
        "max_participants",
        "min_participants",
        "duration",
        "desired_slot_nb",
        "available_friday_evening",
        "available_friday_night",
        "available_saturday_morning",
        "available_saturday_afternoon",
        "available_saturday_evening",
        "available_saturday_night",
        "available_sunday_morning",
        "available_sunday_afternoon",
        "constraints",
        "needs",
        "comments",
    ]


class ExportSlots(SuperuserRequiredMixin, CSVWriteView):
    filename = "créneaux_48h"
    headers = [
        "Titre",
        "Début",
        "Salle",
        "Affiché sur le planning",
        "Affiché sur l'activité" "Couleur",
        "Durée",
        "Durée activité",
    ]

    def get_rows(self):
        slots = models.SlotModel.objects.all()
        rows = []
        for slot in slots:
            rows.append(
                [
                    str(slot),
                    slot.start,
                    slot.room,
                    slot.on_planning,
                    slot.on_activity,
                    Colors(slot.color).name,
                    slot.duration,
                    slot.activity.duration,
                ]
            )
        return rows


# ==============================
# Send email views
# ==============================


# Subject, Message, From, To
EMAIL = Tuple[str, str, Optional[str], List[str]]


class NewEmail(SuperuserRequiredMixin, FormView):
    """Créer un nouveau mail"""

    template_name = "send_email.html"
    form_class = SendEmailForm
    success_url = reverse_lazy("admin_pages:index")
    from_address = None

    def get_emails(self) -> List[str]:
        """return the list of destination emails"""
        users = User.objects.filter(is_active=True)
        return [u.email for u in users]

    @staticmethod
    def sending_allowed() -> bool:
        """Checks if sending mass emails is allowed"""
        settings = SiteSettings.load()
        return settings.allow_mass_mail

    def form_valid(self, form: SendEmailForm) -> HttpResponse:
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        if not self.sending_allowed():
            messages.error(self.request, "L'envoi de mail de masse est désactivé dans les réglages")
        else:
            subject = form.cleaned_data["subject"]
            text = form.cleaned_data["text"]
            emails = []
            for to_addr in self.get_emails():
                emails.append([subject, text, self.from_address, [to_addr]])
            nb_sent = send_mass_mail(emails, fail_silently=False)
            mail_admins(
                "Email envoyé",
                "Un email a été envoyé à tous les utilisateurs.\n"
                "Nombre total de mail envoyés: {}\n\n"
                "Sujet : {}\n\n"
                "{}\n\n"
                "{}".format(
                    nb_sent,
                    subject,
                    text,
                    settings.EMAIL_SIGNATURE,
                ),
            )
            messages.success(self.request, "{} mails envoyés".format(nb_sent))
        return super().form_valid(form)

    def get_context_data(self, *args, **kwargs) -> Dict[str, str]:

admin_pages/templates/admin.html
{% extends "base.html" %}
{% load static %}
{% block nav_admin %}current{% endblock %}

{% block head %}
<script src="{% static 'js/vis-timeline.min.js' %}"></script>
{% endblock %}

{% block "content" %}
	<h2>Page d'administration</h2>
	<p><strong>Version {{ constants.WEBSITE_FULL_VERSION }} &mdash; Django {{ django_version }}</strong></p>
	
	<p>
		Bienvenue sur la page d'administration du site! Si c'est votre première venue
		ici, je recommande vivement de lire le <a href="{% url 'admin_pages:info' %}">guide de l'administrateur</a>.
	</p>
	
	<ul class="messagelist">
		<li class="warning">
			En tant qu'administrateur, vous êtes responsables de la gestion de données
			personnelles stockées sur ce site (essentiellement les emails des orgas,
			mais aussi d'éventuelles détails personnels qu'ils peuvent rajouter dans 
			les champs additionnels des propositions d'activités).

			<p>Une fois l'évènement terminée, vous êtes également responsable de la suppression
			de ces données de la base de donnée, ainsi que de toutes les copies/export
			qui en ont été faites. J'imagine qu'on peut garder les noms et emails en privé
		  à des fins d'historique (sauf si on reçoit une demande explicite de suppression
			de données), mais toute information plus personnelle doit être retirée.</p>
		</li>
	</ul>
	
	<div class="flex wrap">
		<a class="button" href="{% url 'admin_pages:activities.csv' %}"><i class="fa fa-download"></i> Activités</a>
		<a class="button" href="{% url 'admin_pages:slots.csv' %}"><i class="fa fa-download"></i> Crénaux</a>
	</div>
	<ul class="messagelist">
		<li class="info">
	Pour plus d'options d'accès et de modifications, aller à la <a href="{% url 'admin:index' %}">page d'administration de django</a>.
	<br>N'y modifiez rien si vous n'êtes pas sûrs de ce que cela fait.
		</li></ul>

	<h2>Paramètres du site</h2>

		<ul>
			<li>Les emails des orgas sont {% if settings.show_host_emails %}affichés sur la page activité{% else %}masqués{% endif %}.</li>
			<li>L'envoi d'email en masse est {% if settings.allow_mass_email %}activé{% else %}désactivé{% endif %}</li>
			<li>Le planning {% if settings.display_planning %}est affiché{% else %}n'est pas affiché{% endif %}.</li>
			<li>{% if settings.global_message %}Un message global est affiché{% else %}Aucun message global{% endif %}.</li>
		</ul>

		<div>
			<a class="button" href="{% url 'admin:site_settings_sitesettings_change' 1 %}">
				<i class="fa fa-cog"></i>
				Modifier les paramètres
			</a>
		</div>

	<h2>Métriques</h2>

	<div class="flex wrap lines">
		<div class="stat">
			<div class="qty">Utilisateurs</div>
			<div class="nb_big">{{ metrics.users }}</div>
		</div>
		<div class="stat">
			<div class="qty">Activités</div>
			<div class="nb_big">{{ metrics.activites }}</div>
		</div>
		<div class="stat">
			<div class="qty">Affichées</div>
			<div class="nb_big">{{ metrics.displayed }}</div>
		</div>
		<div class="stat">
			<div class="qty">sur inscription</div>
			<div class="nb_big">{{ metrics.act_ins }}</div>
		</div>
		<div class="stat">
			<div class="qty">Planning</div>
			<div class="nb_big">{{ metrics.slots }}</div>
		</div>

	</div>

	<h2>Prévisualisation du planning</h2>

	<ul class="messagelist">
		{{ planning_validation|safe }}
	</ul>

	<p>
		Vous pouvez uploader une version PDF (plus lisible sur mobile) dans les paramètres du site
		(depuis la <a href="{% url 'admin:index' %}">page d'administration de django</a>).
	</p>

	<p>
		Vous pouvez avoir une activité affichée uniquement dans le planning
		(son créneau est affiché, mais l'activité ne l'est pas). C'est utile pour éviter
		d'encombrer la page
		<a href="{% url 'pages:html_page' slug='activites' %}" rel="text/html">activités</a>
		avec des activités à descriptions évidentes (par exemple les repas).
	</p>

	{% include "_planning.html" %}

	<h2>Mail aux utilisateurs</h2>

	<p>Écrire un mail à tous les utilisateurs</p>

	<p>Évitez de spammer. N'envoyez que si vraiment nécessaire.</p>

	<p><a class="button{% if not settings.allow_mass_mail %} disabled{% endif %}" href="{% url 'admin_pages:email_new' %}">Écrire un nouveau mail</a></p>
{% endblock %}

admin_pages/templates/info.html
{% extends "base.html" %}
{% load static %}

{% block "content" %}
<h2>Guide de l'administrateur</h2>

<p>
  Cette page explique un peu comment fonctionne le site et les étapes à suivre pour
  s'en servir lors des 48h des Jexu.
</p>

<h3>À quoi peut servir ce site</h3>

<p><strong>Ce site permet de :</strong>
<ul>
  <li>
    Afficher des informations sur l'événement
    (page d'<a href="{% url 'pages:home' %}">accueil</a>
    et <a href="{% url 'pages:html_page' slug='faq' %}">FAQ</a>,
    modifiable directement depuis l'une des <a href="{% url 'admin:pages_htmlpagemodel_changelist' %}">pages d'admin de
      django</a>)
  </li>
  <li>Recenser les activités proposées (page <a href="{% url 'pages:html_page' slug='activites' %}">activités</a>)</li>
  <li>
    Un formulaire pour permettre aux gens de <a href="{% url 'activity_submission' %}">proposer des activités</a>
    qui envoie un mail aux administrateurs à chaque fois qu'une nouvelle activité
    est proposée.
  </li>
  <li>
    Afficher un planning dynamique des différentes activités (page <a
      href="{% url 'pages:html_page' slug='activites' %}">activités</a>)
  </li>
  <li>Un formulaire pour envoyer un mail à tous (à utiliser avec modération)</li>
  <li>Exporter les tables intéressantes au format CSV (depuis la <a href="{% url 'admin_pages:index' %}">page
      d'administration</a>)</li>
</ul>
</p>

<h3>Pages d'administrations</h3>

<p>Le site web se gère depuis deux pages d'administration :</p>

<p><strong><a href="{% url 'admin_pages:index' %}">La page d'administration du site</a></strong>
  dont vous venez probablement.
  Elle sert principalement à afficher l'état du site et envoyer des mails:
<ul>
  <li>permet d'exporter les différentes tables au format CSV</li>
  <li>affiche l'état du site (version, réglages actuels, différentes métriques)</li>
  <li>une prévisualisation du planning</li>
  <li>permet l'écriture d'un mail à tous</li>
</ul>
</p>

<p>
  <strong><a href="{% url 'admin:index' %}">La page d'administration Django</a></strong>
  est autogénéré à partir des tables de la base de donnée. Elle permet de les modifier
  directement. Voici un descriptif rapide des tables intéressantes :
<ul>
  <li>
    <strong>Utilisateurs</strong> - contient tous les utilisateurs et leurs permissions. Pour
    donner les droits d'administrateur à quelqu'un il faut lui donner le statut
    superuser (accès à l'admin du site) ET le statut équipe (accès à l'admin
    django).
  </li>
  <li>
    <strong>Pages HTML</strong> - contient les pages d'informations (notamment home, activités et
    FAQ). Cela permet aux administrateurs de modifier leur contenu facilement
    depuis le site en ligne, sans avoir à accéder au serveur. Ces pages ont un nom
    (uniquement visible dans l'admin), un URL d'accès et un contenu (format HTML
    avec tags de templates django).

    Les pages "home" (url vide) "activites" et "faq" sont spéciales. Elles
    apparaissent sur la barre de navigation et sont régénérées à partir de
    fichiers de base dans pages/default/ si quelqu'un tente
    d'y accéder après leur suppression.

    Vous pouvez créer d'autres pages sur des URL libres si ça vous semble pertinent.

    Les autres pages du site (formulaires, pages de connexion...) sont des
    templates django plus classiques et ne peuvent être modifié que depuis le code
    source.
  </li>
  <li>
    <strong>Paramètres</strong> - les réglages du site, ils permettent :
    <ul>
      <li>ouvrir/fermer le formulaire de proposition d'activités</li>
      <li>afficher/cacher le planning</li>
      <li>renseigner l'email de contact, les dates de l'événement</li>
      <li>ajouter un message global au-dessus de toutes les pages</li>
      <li>bloquer/autoriser l'envoi d'email globaux (pour éviter les envois accidentels)</li>
      <li>ajouter une version PDF du planning (pour affichage sur mobiles)</li>
      <li>ajouter l'affiche (visible sur la page d'accueil)</li>
    </ul>
    De nombreux champs dans les paramètres sont purement informationnels et ne servent
    qu'à mettre à jour l'affichage dans certaines pages, mais certains servent
    à activer/désactiver des fonctionnalités du site (inscription, soumission d'activités, ...).
  </li>

  <li>
    <strong>Activités</strong> liste des activités prévues. C'est ici que vous pouvez
    rajouter/modifier les activités qui s'affichent sur la page activité. Un
    formulaire permet aux utilisateurs de proposer des activités directement. Il
    vous faudra les relire et les valider ensuite manuellement pour qu'elles
    soient affichées sur le site.
  </li>
  <li>
    <strong>Créneaux</strong> - place une activité sur le planning. Une activité peut avoir
    plusieurs créneaux si elle a lieu plusieurs fois. Noter que les inscriptions
    se font à des créneaux et non a des activités.

    Note : le planning généré par le site (en JS) est difficilement lisible sur
    mobile. Le site permet d'uploader une version PDF propre pour mobiles.
    Personnellement je faisais une capture d'écran du planning (vu sur un grand
    écran) que j'exportais en PDF.
  </li>
</ul>
</p>

<h3>Guide pas à pas</h3>

<p>Les grandes étapes de la gestion du site des interludes sont&nbsp;:</p>
<ol>
  <li>
    Dans un premier temps : créer ou réclamer des comptes administrateurs pour
    les organisateurs (normalement si vous voyez cette page vous en avez un!).
    Pour ajouter un nouvel utilisateur en administrateur,
    dites-lui de se créer un compte; enfin trouvez le dans la
    <a href="{% url 'admin:auth_user_changelist' %}">liste des utilisateurs</a>
    et cochez les cases "Statut super-utilisateur" et "statut équipe".
  </li>
  <li>
    Lorsque vous êtes prêt à communiquer autour de l'évènement, allez dans les
    <a href="{% url 'admin:site_settings_sitesettings_change' 1 %}">paramètres</a>
    et remplissez toutes les informations pertinentes (dates, affiche...).
    Si vous n'avez pas encore toutes les infos vous pouvez
    toujours les rajouter/modifier plus tard. Faites ensuite un tour sur les différentes
    pages publiques du site
    (<a href="{% url 'pages:home' %}">accueil</a>,
    <a href="{% url 'pages:html_page' slug='faq' %}">FAQ</a>,
    <a href="{% url 'pages:html_page' slug='activites' %}">activités</a>,
    <a href="{% url 'pages:html_page' slug='legal' %}">mentions légales</a>...)
    Pour vérifier que toutes les informations sont correctes. Au besoin, vous pouvez
    modifier ces pages depuis l'une des <a href="{% url 'admin:pages_htmlpagemodel_changelist' %}">pages d'admin de
      django</a>.
  </li>
  <li>
    La première phase est l'appel à activités&nbsp;: pour ce faire, il faut ouvrir la
    création de compte et l'ajout d'activités dans les <a
      href="{% url 'admin:site_settings_sitesettings_change' 1 %}">paramètres</a>.
    N'importe qui peut alors proposer une activité via <a href="{% url 'activity_submission' %}">le formulaire</a>.
    (Un paramètre permet d'être notifié par mail à chaque fois qu'une activité est proposée).
    Par mesure de sécurité, les nouvelles activités proposées ne sont pas directement affichées.
    Il faut que vous alliez dans la <a href="{% url 'admin:home_activitymodel_changelist' %}">liste des activités (admin
      django)</a>
    pour les approuver. Pour les activités sur inscriptions, il faut afficher l'email
    de l'organisateur afin qu'il puisse être contacté par les personnes voulant s'inscrire.
  </li>
  <li>
    Une fois l'appel d'activités terminé, fermez l'ajout d'activités et faites le
    planning. Pour rentrer le planning dans le site web, il faut ajouter (au moins)
    un créneau par activité, depuis
    <a href="{% url 'admin:home_slotmodel_changelist' %}">la page d'admin de django</a>,
    en précisant l'heure et le lieu où aura lieu l'activité. Vous pouvez ensuite
    voir une prévisualisation du planning sur la
    <a href="{% url 'admin_pages:index' %}">page d'admin</a>. Si vous êtes satisfait
    du rendu, vous pouvez aller dans les <a href="{% url 'admin:site_settings_sitesettings_change' 1 %}">paramètres</a>
    pour afficher le planning.
  </li>
  <li>
    Envoyer un mail à diff-cof pour annoncer l'événement et proposer aux intéressés
    de prendre contact avec les MJs des activités auxquelles ils veulent participer.
  </li>
</ol>

<h3>Contact support</h3>

<p>
  Ce site web a été crée par Dorian Lesbre pour les
  Interludes 2021. N'hésitez pas à me contacter en cas de soucis.
  Vous trouverez des informations de contact à jour sur
  <a href="https://www.normalesup.org/~dlesbre/">mon site web</a>.
</p>

{% endblock %}

admin_pages/templates/send_email.html
{% extends "base.html" %}
{% load static %}

{% block "content" %}
<h2>Envoyer un email</h2>

<p>
	Ce formulaire permet d'envoyer un mail à tous les comptes du site.
	À utiliser avec modération.
</p>

<form method="post" action="{% url 'admin_pages:email_new' %}">
	{% csrf_token %}
	<table>
		<tr><td><strong>De :</strong></td><td>{{ from_email }}</td></tr>
		<tr><td><strong>Envoyer à : <strong></td><td>tous les inscrits ({{ accounts_nb }} personnes)</td></tr>
		<tr><td><strong>Sujet : <strong></td><td>{{ form.subject }}</td></tr>
	</table>
	{{ form.text }}
	<br>
	<div class="flex">
		<input type="submit" value="Envoyer">
		<a class="button" href="{% url 'admin_pages:index' %}">Annuler</a>
	</div>
</form>
{% endblock %}